import { useState, useEffect, useMemo, useCallback } from 'react'
import { Plus, Pencil, Trash2, Search, X, FileSpreadsheet, FileText, Loader2, AlertTriangle, Wrench, ChevronLeft, ChevronRight } from 'lucide-react'
import * as XLSX from 'xlsx'
import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import { supabase } from '../../../lib/supabase'

interface Item { id: number; name: string; created_at: string }
const PAGE_SIZE = 10
const TABLE = 'machine_types'
const TITLE = 'Machine Type'

const inputCls = `w-full bg-bg-elevated border border-border rounded-xl px-4 py-2.5 text-[13.5px] text-ink-primary placeholder-ink-muted focus:outline-none focus:border-primary/60 focus:ring-2 focus:ring-primary/15 hover:border-border-bright transition-[border-color,box-shadow] duration-200`
function Backdrop({ c }: { c: React.ReactNode }) { return <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm">{c}</div> }
function Card({ c }: { c: React.ReactNode }) { return <div className="bg-bg-surface border border-border rounded-2xl w-full max-w-sm" style={{ boxShadow:'0 32px 80px rgba(0,0,0,0.7),0 0 0 1px rgba(255,255,255,0.04)' }}>{c}</div> }

export default function MachineType() {
  const [items,setItems]=useState<Item[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const [flash,setFlash]=useState<string|null>(null)
  const [search,setSearch]=useState('');const [page,setPage]=useState(1)
  const [addOpen,setAddOpen]=useState(false);const [editItem,setEditItem]=useState<Item|null>(null);const [delItem,setDelItem]=useState<Item|null>(null)
  const [name,setName]=useState('');const [formErr,setFormErr]=useState<string|null>(null);const [saving,setSaving]=useState(false)
  const showFlash=(m:string)=>{setFlash(m);setTimeout(()=>setFlash(null),3000)}
  const load=useCallback(async()=>{setLoading(true);const{data,error:e}=await supabase.from(TABLE).select('*').order('name');if(e)setError(e.message);else setItems((data as Item[])??[]);setLoading(false)},[])
  useEffect(()=>{load()},[load])
  const filtered=useMemo(()=>items.filter(i=>i.name.toLowerCase().includes(search.toLowerCase())),[items,search])
  const totalPages=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE));const paged=filtered.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE)
  useEffect(()=>setPage(1),[search])
  const openAdd=()=>{setName('');setFormErr(null);setAddOpen(true)}
  const openEdit=(it:Item)=>{setName(it.name);setFormErr(null);setEditItem(it)}
  async function doAdd(){if(!name.trim()){setFormErr('Name is required.');return}setSaving(true);setFormErr(null);const{error:e}=await supabase.from(TABLE).insert({name:name.trim()});if(e){setFormErr(e.message);setSaving(false);return}setAddOpen(false);showFlash(`${TITLE} added.`);load();setSaving(false)}
  async function doEdit(){if(!editItem||!name.trim()){setFormErr('Name is required.');return}setSaving(true);setFormErr(null);const{error:e}=await supabase.from(TABLE).update({name:name.trim()}).eq('id',editItem.id);if(e){setFormErr(e.message);setSaving(false);return}setEditItem(null);showFlash(`${TITLE} updated.`);load();setSaving(false)}
  async function doDel(){if(!delItem)return;setSaving(true);const{error:e}=await supabase.from(TABLE).delete().eq('id',delItem.id);if(e)setError(e.message);else{showFlash(`${TITLE} deleted.`);load()}setDelItem(null);setSaving(false)}
  function exportXlsx(){const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(filtered.map((r,i)=>({'#':i+1,Name:r.name}))),TITLE);XLSX.writeFile(wb,`${TABLE}.xlsx`)}
  function exportPdf(){const doc=new jsPDF();doc.setFontSize(13);doc.text(`Rational Construction Pvt. Ltd. — ${TITLE}`,14,14);autoTable(doc,{startY:22,head:[['#','Name']],body:filtered.map((r,i)=>[i+1,r.name]),headStyles:{fillColor:[90,127,255]},styles:{fontSize:9}});doc.save(`${TABLE}.pdf`)}

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center gap-3">
        <div className="flex-1"><h2 className="font-display text-[20px] font-bold text-ink-primary tracking-[-0.03em]">{TITLE}</h2><p className="text-ink-muted text-[13px] mt-0.5">{items.length} record{items.length!==1?'s':''}</p></div>
        <div className="flex items-center gap-2">
          <button onClick={exportXlsx} className="flex items-center gap-2 px-3 py-2 rounded-xl bg-bg-elevated border border-border text-ink-secondary hover:bg-white/[0.06] hover:text-ink-primary text-[12px] font-medium transition-colors duration-150"><FileSpreadsheet className="w-3.5 h-3.5 text-success"/>Excel</button>
          <button onClick={exportPdf}  className="flex items-center gap-2 px-3 py-2 rounded-xl bg-bg-elevated border border-border text-ink-secondary hover:bg-white/[0.06] hover:text-ink-primary text-[12px] font-medium transition-colors duration-150"><FileText className="w-3.5 h-3.5 text-danger"/>PDF</button>
          <button onClick={openAdd} className="flex items-center gap-2 px-4 py-2 rounded-xl bg-primary hover:bg-primary-dark text-white text-[13px] font-semibold transition-[background-color] duration-150" style={{boxShadow:'0 4px 14px rgba(90,127,255,0.35)'}}><Plus className="w-4 h-4"/>Add {TITLE}</button>
        </div>
      </div>
      {flash&&<div className="flex items-center gap-2.5 bg-success/10 border border-success/25 rounded-xl px-4 py-3 text-[13px] text-success"><span className="w-2 h-2 rounded-full bg-success shrink-0"/>{flash}</div>}
      {error&&<div className="flex items-center gap-2.5 bg-danger/10 border border-danger/25 rounded-xl px-4 py-3 text-[13px] text-danger"><AlertTriangle className="w-4 h-4 shrink-0"/>{error}</div>}
      <div className="relative"><Search className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-ink-muted pointer-events-none"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search…" className={`${inputCls} pl-10 pr-10`}/>{search&&<button onClick={()=>setSearch('')} className="absolute right-3 top-1/2 -translate-y-1/2 text-ink-muted hover:text-ink-secondary"><X className="w-4 h-4"/></button>}</div>
      <div className="bg-bg-surface border border-border rounded-2xl overflow-hidden" style={{boxShadow:'0 4px 24px rgba(0,0,0,0.25)'}}>
        {loading?(<div className="flex items-center justify-center py-20 gap-3"><Loader2 className="w-5 h-5 animate-spin text-primary"/><span className="text-[13px] text-ink-muted">Loading…</span></div>):paged.length===0?(<div className="flex flex-col items-center justify-center py-20 gap-3"><Wrench className="w-10 h-10 text-ink-muted/40"/><p className="text-ink-muted text-[13px]">{search?'No results.':'No machine types yet.'}</p></div>):(
          <table className="w-full text-[13px]"><thead><tr className="border-b border-border bg-bg-elevated/50">{['#','Name','Actions'].map(h=><th key={h} className="text-left text-[10px] font-semibold text-ink-muted uppercase tracking-[0.08em] px-4 py-3">{h}</th>)}</tr></thead>
          <tbody className="divide-y divide-border/50">{paged.map((it,i)=>(<tr key={it.id} className="hover:bg-white/[0.02] transition-colors duration-100"><td className="px-4 py-3 text-ink-muted">{(page-1)*PAGE_SIZE+i+1}</td><td className="px-4 py-3 font-medium text-ink-primary">{it.name}</td><td className="px-4 py-3"><div className="flex items-center gap-1.5"><button onClick={()=>openEdit(it)} className="p-1.5 rounded-lg text-accent/80 hover:text-accent hover:bg-accent/10 transition-colors duration-150"><Pencil className="w-3.5 h-3.5"/></button><button onClick={()=>setDelItem(it)} className="p-1.5 rounded-lg text-danger/70 hover:text-danger hover:bg-danger/10 transition-colors duration-150"><Trash2 className="w-3.5 h-3.5"/></button></div></td></tr>))}</tbody></table>
        )}
      </div>
      {totalPages>1&&<div className="flex items-center justify-between text-[12px] text-ink-muted"><span>Showing {(page-1)*PAGE_SIZE+1}–{Math.min(page*PAGE_SIZE,filtered.length)} of {filtered.length}</span><div className="flex items-center gap-1"><button onClick={()=>setPage(p=>Math.max(1,p-1))} disabled={page===1} className="p-1.5 rounded-lg hover:bg-white/[0.06] disabled:opacity-40"><ChevronLeft className="w-4 h-4"/></button>{Array.from({length:totalPages},(_,i)=>i+1).map(n=><button key={n} onClick={()=>setPage(n)} className={`w-7 h-7 rounded-lg text-[12px] font-medium transition-colors duration-150 ${n===page?'bg-primary text-white':'hover:bg-white/[0.06] text-ink-secondary'}`}>{n}</button>)}<button onClick={()=>setPage(p=>Math.min(totalPages,p+1))} disabled={page===totalPages} className="p-1.5 rounded-lg hover:bg-white/[0.06] disabled:opacity-40"><ChevronRight className="w-4 h-4"/></button></div></div>}
      {addOpen&&<Backdrop c={<Card c={<><div className="flex items-center justify-between px-6 pt-5 pb-4 border-b border-border"><h3 className="font-display text-[16px] font-bold text-ink-primary">Add {TITLE}</h3><button onClick={()=>setAddOpen(false)} className="p-1.5 rounded-lg text-ink-muted hover:bg-white/[0.06] transition-colors duration-150"><X className="w-4 h-4"/></button></div><div className="px-6 py-5 space-y-4"><div className="space-y-1.5"><label className="block text-[11px] font-semibold text-ink-secondary uppercase tracking-[0.08em]">Name *</label><input value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>e.key==='Enter'&&doAdd()} placeholder="e.g. JCB Excavator" className={inputCls} autoFocus/></div>{formErr&&<div className="flex gap-2 bg-danger/10 border border-danger/25 rounded-xl px-4 py-3 text-[13px] text-danger"><AlertTriangle className="w-4 h-4 shrink-0 mt-0.5"/>{formErr}</div>}</div><div className="px-6 pb-5 flex justify-end gap-2.5"><button onClick={()=>setAddOpen(false)} className="px-4 py-2 rounded-xl border border-border text-ink-secondary hover:bg-white/[0.05] text-[13px] font-medium transition-colors duration-150">Cancel</button><button onClick={doAdd} disabled={saving} className="flex items-center gap-2 px-4 py-2 rounded-xl bg-primary hover:bg-primary-dark disabled:opacity-60 text-white text-[13px] font-semibold transition-[background-color] duration-150">{saving&&<Loader2 className="w-3.5 h-3.5 animate-spin"/>}{saving?'Adding…':'Add'}</button></div></>}/>}/>}
      {editItem&&<Backdrop c={<Card c={<><div className="flex items-center justify-between px-6 pt-5 pb-4 border-b border-border"><h3 className="font-display text-[16px] font-bold text-ink-primary">Edit {TITLE}</h3><button onClick={()=>setEditItem(null)} className="p-1.5 rounded-lg text-ink-muted hover:bg-white/[0.06] transition-colors duration-150"><X className="w-4 h-4"/></button></div><div className="px-6 py-5 space-y-4"><div className="space-y-1.5"><label className="block text-[11px] font-semibold text-ink-secondary uppercase tracking-[0.08em]">Name *</label><input value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>e.key==='Enter'&&doEdit()} className={inputCls} autoFocus/></div>{formErr&&<div className="flex gap-2 bg-danger/10 border border-danger/25 rounded-xl px-4 py-3 text-[13px] text-danger"><AlertTriangle className="w-4 h-4 shrink-0 mt-0.5"/>{formErr}</div>}</div><div className="px-6 pb-5 flex justify-end gap-2.5"><button onClick={()=>setEditItem(null)} className="px-4 py-2 rounded-xl border border-border text-ink-secondary hover:bg-white/[0.05] text-[13px] font-medium transition-colors duration-150">Cancel</button><button onClick={doEdit} disabled={saving} className="flex items-center gap-2 px-4 py-2 rounded-xl bg-accent hover:bg-accent/90 disabled:opacity-60 text-bg-base text-[13px] font-semibold transition-[background-color] duration-150">{saving&&<Loader2 className="w-3.5 h-3.5 animate-spin"/>}{saving?'Saving…':'Save'}</button></div></>}/>}/>}
      {delItem&&<Backdrop c={<Card c={<><div className="px-6 pt-6 pb-5 text-center"><div className="w-12 h-12 rounded-full bg-danger/15 border border-danger/30 flex items-center justify-center mx-auto mb-4"><AlertTriangle className="w-5 h-5 text-danger"/></div><h3 className="font-display text-[16px] font-bold text-ink-primary mb-1">Delete?</h3><p className="text-ink-muted text-[13px]">Remove <span className="text-ink-primary font-medium">"{delItem.name}"</span>?</p></div><div className="px-6 pb-5 flex gap-2.5"><button onClick={()=>setDelItem(null)} className="flex-1 px-4 py-2 rounded-xl border border-border text-ink-secondary hover:bg-white/[0.05] text-[13px] font-medium transition-colors duration-150">Cancel</button><button onClick={doDel} disabled={saving} className="flex-1 flex items-center justify-center gap-2 px-4 py-2 rounded-xl bg-danger hover:bg-danger/90 disabled:opacity-60 text-white text-[13px] font-semibold transition-[background-color] duration-150">{saving&&<Loader2 className="w-3.5 h-3.5 animate-spin"/>}{saving?'Deleting…':'Delete'}</button></div></>}/>}/>}
    </div>
  )
}
